language: python
cache: pip

services:
  - postgresql

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1

matrix:
  fast_finish: true
  include:
    - { python: "3.8", env: TOXENV=isort }
    # - { python: "3.8", env: TOXENV=docs }

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
